// main.slint
import { AppWindow } from "./appwindow.slint";
import { SettingsWindow } from "./settings_window.slint";
import { ThumbnailWindow, Thumbnail } from "./thumbnail_window.slint";
import { ColorCorrectionWindow } from "./color_correction_window.slint";
import { Theme } from "./theme.slint";
import { Palette } from "std-widgets.slint";

// Export all components used on the Rust side
export { AppWindow, SettingsWindow, ThumbnailWindow, Thumbnail, ColorCorrectionWindow, Theme, Palette }
