export global Theme {
    // menu bar
    in-out property <length> menu-bar-height: 40px;
    in-out property <color> menu-bar-background: #191919;
    // tool button
    in-out property <color> tool-button-background: #3a3a3a;
    in-out property <color> tool-button-border-color: #555;
    in-out property <color> tool-button-color: #9198A1;
    // status bar
    in-out property <length> status-bar-height: 40px; // 28px 
    in-out property <color> status-bar-background: #191919;
    in-out property <color> status-bar-color: #9198A1;
    // image container
    in-out property <color> image-container-background: #1E1E1E;
}