import { ScrollView } from "std-widgets.slint";

export struct Thumbnail {
    source: image,
    path: string,
}

export component ThumbnailWindow inherits Window {
    title: "Thumbnails";
    min-width: 210px;
    min-height: 210px;
    preferred-width: 210px;
    preferred-height: 600px;

    in property <[Thumbnail]> thumbnails;
    in-out property <string> selected-path;
    callback hide();
    callback thumbnail_clicked(string);
    callback next_image();
    callback previous_image();
    callback move_selection(int);

    private property <length> thumb-size: 100px;
    private property <length> spacing: 10px;
    private property <int> columns: Math.floor(root.width / (thumb-size + spacing));
    private property <int> rows: Math.ceil(root.thumbnails.length / root.columns);

    forward-focus: key_handler;
    key_handler := FocusScope {
        key-pressed(event) => {
            if (event.text == Key.Escape) {
                root.hide();
            }
            if (event.text == Key.LeftArrow || ((event.text == Key.LeftArrow) && event.modifiers.alt)) {
                root.previous_image();
            }
            if (event.text == "A" || event.text == "a") {
                root.previous_image();
            }
            if (event.text == Key.RightArrow || ((event.text == Key.RightArrow) && event.modifiers.alt)) {
                root.next_image();
            }
            if (event.text == "D" || event.text == "d") {
                root.next_image();
            }
            if (event.text == Key.UpArrow || event.text == "W" || event.text == "w") {
                root.move_selection(-root.columns);
            }
            if (event.text == Key.DownArrow || event.text == "S" || event.text == "s") {
                root.move_selection(root.columns);
            }
            accept // Consume event
        }
    }

    ScrollView {
        viewport-height: root.rows * (root.thumb-size + root.spacing) + root.spacing;
        Rectangle {
            width: 100%;
            height: 100%;
            for thumb[i] in root.thumbnails : _touch := TouchArea {
                width: root.thumb-size;
                height: root.thumb-size;
                x: root.spacing + Math.mod(i, root.columns) * (root.thumb-size + root.spacing);
                y: root.spacing + Math.floor(i / root.columns) * (root.thumb-size + root.spacing);
                Rectangle {
                    border-width: (thumb.path == root.selected-path) ? 2px : 1px;
                    border-color: (thumb.path == root.selected-path) ? green : (_touch.has-hover ? #555 : #191919);
                    background: _touch.pressed ? #282828 : _touch.has-hover ? #3a3a3a :  #282828;
                    Image {
                        source: thumb.source;
                        width: 92%;
                        height: 92%;
                        image-fit: contain;
                    }
                }
                clicked => { root.thumbnail_clicked(thumb.path); }
            }
        }
    }
}
