import { ScrollView } from "std-widgets.slint";

export struct Thumbnail {
    source: image,
    path: string,
}

export component ThumbnailWindow inherits Window {
    title: "Thumbnails";
    min-width: 210px;
    min-height: 210px;
    preferred-width: 210px;
    preferred-height: 600px;

    in property <[Thumbnail]> thumbnails;
    callback thumbnail_clicked(string);

    private property <length> thumb-size: 100px;
    private property <length> spacing: 10px;
    private property <int> columns: Math.floor(root.width / (thumb-size + spacing));
    private property <int> rows: Math.ceil(root.thumbnails.length / root.columns);

    ScrollView {
        viewport-height: root.rows * (root.thumb-size + root.spacing);
        Rectangle {
            width: 100%;
            height: 100%;
            for thumb[i] in root.thumbnails : TouchArea {
                width: root.thumb-size;
                height: root.thumb-size;
                x: root.spacing + Math.mod(i, root.columns) * (root.thumb-size + root.spacing);
                y: root.spacing + Math.floor(i / root.columns) * (root.thumb-size + root.spacing);
                Image {
                    source: thumb.source;
                    width: 100%;
                    height: 100%;
                    image-fit: contain;
                }
                clicked => { root.thumbnail_clicked(thumb.path); }
            }
        }
    }
}