use slint::{Image, SharedPixelBuffer};

// Use the UI generated by `build.rs`
slint::include_modules!();

const TEST_IMAGE_PATH: &str = "C:/Users/Yoshinori/projects/oculante/tests/test.png";

fn main() -> Result<(), slint::PlatformError> {
    let ui = AppWindow::new()?;

    // Load an image using the `image` crate
    let image_data = image::open(TEST_IMAGE_PATH)
        .expect("Failed to open test image")
        .to_rgb8();
    
    let image_width = image_data.width();
    let image_height = image_data.height();

    // Create a Slint image from the loaded data
    let slint_image = Image::from_rgb8(
        SharedPixelBuffer::clone_from_slice(
            image_data.as_raw(),
            image_width,
            image_height
        )
    );

    ui.set_image_display(slint_image);

    ui.run()
}